server:
  shutdown: graceful
inject:
  value: injectValueInYml
spring:
  lifecycle:
    timeout-per-shutdown-phase: 60s
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: boot-example