spring:
  kafka:
    bootstrap-servers:
      - localhost:55000
      - localhost:55001
      - localhost:55002
    producer:
      acks: all # ack设置为all，保证消息服务器主题分区中的leader和flower同步完成并写入日志文件
      batch-size: 16384 # 批量发送大小16k
      buffer-memory: 33554432 # 缓存区大小为32M
      retries: 3 # 重试次数为3次
    listener:
      ack-mode: MANUAL