spring:
  kafka:
    bootstrap-servers: # 设置kafka服务器列表
      - localhost:9092
    consumer:
      properties:
        max:
          poll:
            interval:
              ms: 300000 # 设置最大轮询间隔，默认值5分钟
        session:
          timeout:
            ms: 45000 # 设置会话超时时间，默认值45秒
        heartbeat:
          interval:
            ms: 3000 # 设置心跳间隔，默认值3秒
      max-poll-records: 500 # 设置最大拉取记录数，默认值500
    listener:
      ack-mode: manual # 设置手动提交