# DataSource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000
      pool-name: Mybatis-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapperLocations: 'classpath*:mapper/**/*.xml'
logging:
  level:
    com:
      zaxxer:
        hikari:
          pool: debug