spring:
  mail:
    host: smtp.qq.com
    username: xxxx@qq.com
    password: zaaa # 需要登录qq邮箱，然后开启smtp服务，会得到一个密码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            starttls:
              required: true